# Generated by Django 5.0.6 on 2025-09-21 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('summary', 'Summary')], max_length=20)),
                ('current_value', models.FloatField(default=0)),
                ('previous_value', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('tags', models.JSONField(default=dict)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('complaints_summary', 'Complaints Summary'), ('department_performance', 'Department Performance'), ('user_activity', 'User Activity'), ('resolution_trends', 'Resolution Trends'), ('feedback_analysis', 'Feedback Analysis'), ('custom', 'Custom Report')], max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('charts_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles that can access this report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='analytics_reports', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Analytics Report',
                'verbose_name_plural': 'Analytics Reports',
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric'), ('table', 'Table'), ('list', 'List'), ('progress', 'Progress Bar')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot')], max_length=20, null=True)),
                ('data_source', models.CharField(max_length=100)),
                ('query_params', models.JSONField(default=dict)),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Refresh interval in seconds')),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=6)),
                ('height', models.PositiveIntegerField(default=4)),
                ('color_scheme', models.JSONField(default=list)),
                ('custom_css', models.TextField(blank=True)),
                ('roles', models.JSONField(default=list, help_text='List of roles that can see this widget')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='dashboard_widgets', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'dashboard_widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('date', models.DateField()),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('new_complaints', models.PositiveIntegerField(default=0)),
                ('resolved_complaints', models.PositiveIntegerField(default=0)),
                ('pending_complaints', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0)),
                ('total_feedback', models.PositiveIntegerField(default=0)),
                ('new_feedback', models.PositiveIntegerField(default=0)),
                ('avg_feedback_rating', models.FloatField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('department_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Performance Snapshot',
                'verbose_name_plural': 'Performance Snapshots',
                'db_table': 'performance_snapshots',
                'ordering': ['-date'],
                'unique_together': {('period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(default=dict)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dashboard',
                'verbose_name_plural': 'User Dashboards',
                'db_table': 'user_dashboards',
            },
        ),
        migrations.CreateModel(
            name='UserDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveIntegerField()),
                ('position_y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('custom_title', models.CharField(blank=True, max_length=200)),
                ('custom_config', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.userdashboard')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dashboardwidget')),
            ],
            options={
                'verbose_name': 'User Dashboard Widget',
                'verbose_name_plural': 'User Dashboard Widgets',
                'db_table': 'user_dashboard_widgets',
                'unique_together': {('user_dashboard', 'widget')},
            },
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='widgets',
            field=models.ManyToManyField(related_name='user_dashboards', through='analytics.UserDashboardWidget', to='analytics.dashboardwidget'),
        ),
        migrations.CreateModel(
            name='MetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analytics.systemmetric')),
            ],
            options={
                'verbose_name': 'Metric History',
                'verbose_name_plural': 'Metric Histories',
                'db_table': 'metric_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric', 'timestamp'], name='metric_hist_metric__4d9653_idx')],
            },
        ),
    ]
